PREFIX base: <http://namespace.com#>
PREFIX ns: <http://zonawifi.linkeddata.org#>
PREFIX ns2: <http://instancias.org/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>


SELECT ?EntidadWifi ?NombreEntidad ?Latitud ?Longitud ?Barrio ?Distrito ?Ciudad
WHERE {
  ?EntidadWifi a ns:EntidadWifi ;
               ns:tenerNombre ?NombreEntidad ;
               ns:tenerLatitud ?Latitud ;
               ns:tenerLongitud ?Longitud ;
               ns:estarEnVia ?Via .

  ?Via ns:estarEnBarrio ?Barrio .
  ?Barrio ns:estarEnDistrito ?Distrito . 
  ?Distrito ns:estarEnCiudad ?Ciudad.
}

SELECT  ?transporte ?wifi
WHERE {
  ?wifi a ns:EntidadWifi .
  ?wifi ns:llegarConTransporte ?Transporte.
  ?transporte ns:compania ?compania.
  FILTER(?compania = "Metro_de_Madrid")
}

SELECT ?tipoNum 
WHERE {
  ?wifi a ns:EntidadWifi .
  ?wifi ns:tipoNum ?tipoNum .
}


SELECT  ?transporte ?linea
WHERE {
  ?wifi a ns:EntidadWifi .
  ?wifi ns:llegarConTransporte ?transporte.
  ?transporte ns:linea ?linea.
}

