# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGIw0mrKKaPQQV9rNm7EiyL7AiFYNX00

**Task 06: Modifying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials"

"""Read the RDF file as shown in class"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""

ns = Namespace("http://somewhere#")
g.add((ns.University, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher,RDFS.subClassOf,ns.Person))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.3: Create a new individual of Researcher named "Jane Smithers"**"""

ns = Namespace("http://somewhere#")
jane_smithers = ns.JaneSmithers
g.add((jane_smithers, RDF.type, ns.Researcher))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.4: Add to the individual JaneSmithers the email address, fullName, given and family names. Use the https://schema.org vocabulary**"""

ns = Namespace("http://somewhere#")
schema = Namespace("https://schema.org/")

g.add((jane_smithers, schema.email, Literal("jane.smithers@example.com")))
g.add((jane_smithers, schema.name, Literal("Jane Smithers")))
g.add((jane_smithers, schema.givenName, Literal("Jane")))
g.add((jane_smithers, schema.familyName, Literal("Smithers")))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.5: Add UPM as the university where John Smith works. Use the "https://example.org/ namespace**"""

ns = Namespace("http://somewhere#")
schema = Namespace("https://schema.org/")
example = Namespace("https://example.org/")

john_smith = ns.JohnSmith
g.add((john_smith, RDF.type, ns.Researcher))

upm = example.UPM
g.add((upm, RDF.type, schema.Organization))
g.add((john_smith, schema.work, upm))

for s, p, o in g:
    print(s, p, o)

"""**Task 6.6: Add that Jown knows Jane using the FOAF vocabulary. Make sure the relationship exists.**"""

from rdflib.namespace import FOAF
ns = Namespace("http://example.org/ns#")
example = Namespace("http://example.org/")
schema = Namespace("http://schema.org/")


g.add((john_smith, schema.affiliation, upm))
g.add((john_smith, FOAF.knows, jane_smithers))

# Imprimir el grafo
for s, p, o in g:
    print(s, p, o)